quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
# Ajustado para permitir acesso simultâneo (Backend + Console)
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/aluguel_db;AUTO_SERVER=TRUE
quarkus.hibernate-orm.database.generation=update
quarkus.h2.console.enabled=true
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080

# Logs para te ajudar a debugar o que está acontecendo no banco
quarkus.log.level=INFO
quarkus.log.category."com.aluguel".level=DEBUG

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*